collection: "https://steamcommunity.com/sharedfiles/filedetails?id=3751594254"

# Синхронизация Mod ID для предметов с несколькими вариантами
# Используйте, если для одного Workshop ID существует несколько Mod ID
syncmod:
  - 2761200458 : "YakiHS"